version: '3'
services:
  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@sit
    volumes:
      - ./database/mysql-lib:/var/lib/mysql
      # - ./database/my.cnf:/etc/my.cnf
      # - ./database/setup/:/docker-entrypoint-initdb.d/
    restart: on-failure
    networks:
    - test-networks
  backend:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql@sit
      - MYSQL_URL=jdbc:mysql://database:3306/task_base?serverTimezone=UTC
    networks:
      - test-networks






networks:
  test-networks:
    driver: bridge


    